In [20]:
import pandas as pd

In [21]:
import os

In [22]:
print(os.listdir("C:/Users/02.felipe.barbosa/Desktop"))

['AcruxMonitorPDV.url', 'BANCOS.rdp', 'Cipa-2024.rdp', 'Cofre_PMP.url', 'desktop.ini', 'FlowRack.csv', 'Fluig.url', 'GERAR OS.lnk', 'GerenciadordeAssinatura.rdp', 'Gerencia_Robos.rdp', 'Melhoria Continua Compartilha.url', 'Niduu.url', 'Qualiex.url', 'SGE.rdp', 'Sitef_Motor.url', 'SoftCom.lnk', 'SysAid.url', 'Teams.url', 'Webmail O365.url', 'Wiki.url', 'Winthor.lnk']

In [33]:
dados = pd.read_csv('C:/Users/02.felipe.barbosa/Desktop/FlowRack.csv', sep = ";")
dados.head(20)

,DATA,NUMOS,CODPROD,TOTAL_VOLUMEM3,DESCRICAO,QTEMCX
0,01/07/2025,78668605.0,54611.0,"0,00091908",ATUM RALADO ROBINSON CRUSOE OLEO,"0,1"
1,01/07/2025,78668605.0,73930.0,"0,02112",CHICLE BUZZY TATTOO TRIBAL UVA,"0,8"
2,01/07/2025,78668605.0,58315.0,"0,018297",FLOCAO DE MILHO DONA CLARA,"0,7"
3,01/07/2025,78668606.0,33469.0,"0,02058684",CHOC.NESTLE PRESTIGIO,"0,5"
4,01/07/2025,78668606.0,77096.0,"0,00229806",CHOC.HERSHEYS SPECIAL DARK 47%CARAM.SALG,"0,3"
5,01/07/2025,78668606.0,32483.0,"0,0017178",CALDO KNORR CARNE,"0,1"
6,01/07/2025,78668606.0,56283.0,"0,00555008",CHOC.NESTLE AO LEITE SUFLAIR DUO,"0,3"
7,01/07/2025,78668606.0,54611.0,"0,00398268",ATUM RALADO ROBINSON CRUSOE OLEO,"0,5"
8,01/07/2025,78668606.0,76476.0,"0,005889",ACHOC.PO NESCAU LT.,"0,2"
9,01/07/2025,78668607.0,7380.0,"0,00025906",DESOD.DOVE ROLL-ON ORIGINAL 48H*,"0,1"
10,01/07/2025,78668607.0,16495.0,"0,00117216",SBT.GRANADO GLICERINA BEBE,"0,1"
11,01/07/2025,78668607.0,29688.0,"0,03136441",LIMP.VEJA M.USO LAVANDA C/ALCOOL,1
12,01/07/2025,78668607.0,56620.0,"0,00171432",SBT.FRANCIS HIDRATANTE BEGE,"0,1"
13,01/07/2025,78668688.0,58315.0,"0,0073188",FLOCAO DE MILHO DONA CLARA,"0,3"
14,01/07/2025,78668688.0,54024.0,"0,005735",FERM.PO ROYAL LEVE12PAGUE11,"0,3"
15,01/07/2025,78668688.0,56633.0,"0,0191856",DROPS FREEGELLS CEREJA CHOCOLATE,1
16,01/07/2025,78668688.0,38440.0,"0,00308518",CHOC.KINDER BUENO WHITE T2,"0,2"
17,01/07/2025,78668688.0,4708.0,"0,00614061",ATUM GOMES DA COSTA SOL.NATURAL,"0,9"
18,01/07/2025,78668689.0,54024.0,"0,005735",FERM.PO ROYAL LEVE12PAGUE11,"0,3"
19,01/07/2025,78668689.0,19460.0,"0,00896896",SARD.88 OLEO,1

In [34]:
display(dados)

,DATA,NUMOS,CODPROD,TOTAL_VOLUMEM3,DESCRICAO,QTEMCX
0,01/07/2025,78668605.0,54611.0,"0,00091908",ATUM RALADO ROBINSON CRUSOE OLEO,"0,1"
1,01/07/2025,78668605.0,73930.0,"0,02112",CHICLE BUZZY TATTOO TRIBAL UVA,"0,8"
2,01/07/2025,78668605.0,58315.0,"0,018297",FLOCAO DE MILHO DONA CLARA,"0,7"
3,01/07/2025,78668606.0,33469.0,"0,02058684",CHOC.NESTLE PRESTIGIO,"0,5"
4,01/07/2025,78668606.0,77096.0,"0,00229806",CHOC.HERSHEYS SPECIAL DARK 47%CARAM.SALG,"0,3"
...,...,...,...,...,...,...
88583,NaN,NaN,NaN,NaN,NaN,NaN
88584,NaN,NaN,NaN,NaN,NaN,NaN
88585,NaN,NaN,NaN,NaN,NaN,NaN
88586,NaN,NaN,NaN,NaN,NaN,NaN
88587,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
display(dados.head(5))

,DATA,NUMOS,CODPROD,TOTAL_VOLUMEM3,DESCRICAO,QTEMCX
0,01/07/2025,78668605.0,54611.0,"0,00091908",ATUM RALADO ROBINSON CRUSOE OLEO,"0,1"
1,01/07/2025,78668605.0,73930.0,"0,02112",CHICLE BUZZY TATTOO TRIBAL UVA,"0,8"
2,01/07/2025,78668605.0,58315.0,"0,018297",FLOCAO DE MILHO DONA CLARA,"0,7"
3,01/07/2025,78668606.0,33469.0,"0,02058684",CHOC.NESTLE PRESTIGIO,"0,5"
4,01/07/2025,78668606.0,77096.0,"0,00229806",CHOC.HERSHEYS SPECIAL DARK 47%CARAM.SALG,"0,3"

In [37]:
print(dados.head(20))

          DATA       NUMOS  CODPROD TOTAL_VOLUMEM3  \
0   01/07/2025  78668605.0  54611.0     0,00091908
1   01/07/2025  78668605.0  73930.0        0,02112
2   01/07/2025  78668605.0  58315.0       0,018297
3   01/07/2025  78668606.0  33469.0     0,02058684
4   01/07/2025  78668606.0  77096.0     0,00229806
5   01/07/2025  78668606.0  32483.0      0,0017178
6   01/07/2025  78668606.0  56283.0     0,00555008
7   01/07/2025  78668606.0  54611.0     0,00398268
8   01/07/2025  78668606.0  76476.0       0,005889
9   01/07/2025  78668607.0   7380.0     0,00025906
10  01/07/2025  78668607.0  16495.0     0,00117216
11  01/07/2025  78668607.0  29688.0     0,03136441
12  01/07/2025  78668607.0  56620.0     0,00171432
13  01/07/2025  78668688.0  58315.0      0,0073188
14  01/07/2025  78668688.0  54024.0       0,005735
15  01/07/2025  78668688.0  56633.0      0,0191856
16  01/07/2025  78668688.0  38440.0     0,00308518
17  01/07/2025  78668688.0   4708.0     0,00614061
18  01/07/2025  78668689.0  54024.0       0,005735
19  01/07/2025  78668689.0  19460.0     0,00896896

                                   DESCRICAO QTEMCX
0           ATUM RALADO ROBINSON CRUSOE OLEO    0,1
1             CHICLE BUZZY TATTOO TRIBAL UVA    0,8
2                 FLOCAO DE MILHO DONA CLARA    0,7
3                      CHOC.NESTLE PRESTIGIO    0,5
4   CHOC.HERSHEYS SPECIAL DARK 47%CARAM.SALG    0,3
5                          CALDO KNORR CARNE    0,1
6           CHOC.NESTLE AO LEITE SUFLAIR DUO    0,3
7           ATUM RALADO ROBINSON CRUSOE OLEO    0,5
8                        ACHOC.PO NESCAU LT.    0,2
9           DESOD.DOVE ROLL-ON ORIGINAL 48H*    0,1
10                SBT.GRANADO GLICERINA BEBE    0,1
11          LIMP.VEJA M.USO LAVANDA C/ALCOOL      1
12               SBT.FRANCIS HIDRATANTE BEGE    0,1
13                FLOCAO DE MILHO DONA CLARA    0,3
14               FERM.PO ROYAL LEVE12PAGUE11    0,3
15          DROPS FREEGELLS CEREJA CHOCOLATE      1
16                CHOC.KINDER BUENO WHITE T2    0,2
17           ATUM GOMES DA COSTA SOL.NATURAL    0,9
18               FERM.PO ROYAL LEVE12PAGUE11    0,3
19                              SARD.88 OLEO      1